# Generated by Django 4.0.6 on 2022-07-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcount',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
